### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ranranking** [openSIMMO/openSIMMO.github.io#29]
- [ ] Make sim controller a plugin
- [x] Add search engine 
- [x] Table of contents on main page

@beniroquai

**Comment by beniroquai** [comment]
The Algolia Search engine was added in 98cd7f6

**Comment by beniroquai** [comment]
Added a little table of content for the different steps. Worth it?

**Comment by beniroquai** [comment]
Regarding the plugin, I have started putting stuff here: https://github.com/openUC2/imswitch-sim
It will not work - yet. We would need to implement the manager. This is currently not tracked by the plugins. But it's doable. We should do that in our Friday session ;)
